services:
  liquid-auth:
    build: .
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-fido}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-algorand}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-algorand}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
volumes:
  mongo:
